### PR TITLE
Lock dandisets during un-embargo

### PR DESCRIPTION
**Pull request by jjnesbitt**
This change will help prevent race conditions that could arise if modifications are allowed while un-embargo is ongoing.

### CODE REVIEW

**Review by waxlamp — APPROVED** [review]
This all looks good.

One note: I didn't realize that we prohibit publishing of embargoed Dandisets. I wonder if we should consider lifting that ban--I can see why it would be useful to be able to do so, though the wording we're using makes it confusing ("it's embargoed... how can I be publishing this?") when really "publish" mostly means to create an immutable snapshot.

**Comment by jjnesbitt** [comment]
> One note: I didn't realize that we prohibit publishing of embargoed Dandisets. I wonder if we should consider lifting that ban--I can see why it would be useful to be able to do so, though the wording we're using makes it confusing ("it's embargoed... how can I be publishing this?") when really "publish" mostly means to create an immutable snapshot.

I thought it was a hard requirement that published dandisets be open access, from more of a NIH policy standpoint.

**Comment by satra** [comment]
> I thought it was a hard requirement that published dandisets be open access, from more of a NIH policy standpoint.

yes, embargoed dandisets should not receive a published doi. publishing is only for non-embargoed dandisets.

in the future we may publish restricted dandisets, but we haven't implemented that yet. 

to speak about roni's point of freezing versions on embargoed data, that's a different feature which we don't have. we should discuss whether that feature should even exist.

**Comment by jjnesbitt** [comment]
@waxlamp I had forgotten to include uploads as a part of the locking, as well as prohibit un-embargo in the first place if there were active uploads. Commits ef7c530 and b789645 cover that.

**Review by waxlamp — CHANGES_REQUESTED** [review]
This looks good to me, with one requested change: within the exception names (and elsewhere as appropriate), please change the "UnEmbargo" capitalization to "Unembargo" (the word is spelled "unembargo", as "one word" and no hyphens, etc.).

**Review by waxlamp — CHANGES_REQUESTED** [review]
The `UnEmbargo` spelling within the exception classes should be shifted to `Unembargo`.

**Review by waxlamp — APPROVED** [review]

**Pull request merged**
