### PR TITLE
Enable path-only changes to metadata to trigger asset change

### LINKED ISSUE #1682: PUT "silently" (returns 200) doesn't rename and doesn't update metadata (path remains old)
User reported that `dandi move` doesn't work : https://github.com/dandi/dandi-cli/issues/1325 .
I have checked `test_move` tests there -- work fine.
I thought it is zarr specific, have tested on sample files including nwb -- indeed `dandi move` doesn't do good.
I have tried on a sample file via copy/pasting metadata in swagger -- seems worked.
Trying in pdb session of dandi-cli -- nope. Here trying to rename from `bar-renamed` to `bar-renamed2` -- see that result contains `bar-renamed` although provided record `bar-renamed2`:

```
(Pdb) p path
'/dandisets/000029/versions/draft/assets/e4032a47-141d-4c4c-84c1-2be3ac5aeb33/'

*(Pdb) p json.dumps(kwargs['json'])
'{"metadata": {"access": [{"status": "dandi:OpenAccess", "schemaKey": "AccessRequirements"}], "@context": "https://raw.githubusercontent.com/dandi/schema/master/releases/0.6.4/context.json", "schemaKey": "Asset", "repository": "http://localhost:8085", "dateModified": "2023-03-16T11:50:06.357489-04:00", "schemaVersion": "0.6.4", "encodingFormat": "application/octet-stream", "wasGeneratedBy": [{"id": "urn:uuid:47f374af-f500-4d10-87ea-ce1dc4e92d45", "name": "Metadata generation", "endDate": "2023-03-16T11:50:06.357462-04:00", "schemaKey": "Activity", "startDate": "2023-03-16T11:50:06.357462-04:00", "description": "Metadata generated by DANDI cli", "wasAssociatedWith": [{"url": "https://github.com/dandi/dandi-cli", "name": "DANDI Command Line Interface", "version": "0.51.0", "schemaKey": "Software", "identifier": "RRID:SCR_019009"}]}], "blobDateModified": "2023-03-13T15:37:42.000759-04:00", "id": "dandiasset:e4032a47-141d-4c4c-84c1-2be3ac5aeb33", "path": "bar-renamed2", "identifier": "e4032a47-141d-4c4c-84c1-2be3ac5aeb33", "contentUrl": ["https://api.dandiarchive.org/api/assets/e4032a47-141d-4c4c-84c1-2be3ac5aeb33/download/", "https://dandiarchive.s3.amazonaws.com/blobs/2fd/746/2fd7464f-5459-4c96-a938-27cf13f4d330"], "contentSize": 4, "digest": {"dandi:dandi-etag": "517a02191c8c9d1013b48b1f295e03a2-1", "dandi:sha2-256": "b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c"}}, "blob_id": "2fd7464f-5459-4c96-a938-27cf13f4d330"}'
(Pdb) p kwargs['json']['metadata']['path']
'bar-renamed2'
(Pdb) self.request("PUT", path, json=kwargs['json'])
{'asset_id': 'e4032a47-141d-4c4c-84c1-2be3ac5aeb33', 'blob': '2fd7464f-5459-4c96-a938-27cf13f4d330', 'zarr': None, 'path': 'bar-renamed', 'size': 4, 'created': '2023-09-15T20:41:51.221272Z', 'modified': '2023-09-15T20:41:51.236057Z', 'metadata': {'access': [{'status': 'dandi:OpenAccess', 'schemaKey': 'AccessRequirements'}], '@context': 'https://raw.githubusercontent.com/dandi/schema/master/releases/0.6.4/context.json', 'schemaKey': 'Asset', 'repository': 'http://localhost:8085', 'dateModified': '2023-03-16T11:50:06.357489-04:00', 'schemaVersion': '0.6.4', 'encodingFormat': 'application/octet-stream', 'wasGeneratedBy': [{'id': 'urn:uuid:47f374af-f500-4d10-87ea-ce1dc4e92d45', 'name': 'Metadata generation', 'endDate': '2023-03-16T11:50:06.357462-04:00', 'schemaKey': 'Activity', 'startDate': '2023-03-16T11:50:06.357462-04:00', 'description': 'Metadata generated by DANDI cli', 'wasAssociatedWith': [{'url': 'https://github.com/dandi/dandi-cli', 'name': 'DANDI Command Line Interface', 'version': '0.51.0', 'schemaKey': 'Software', 'identifier': 'RRID:SCR_019009'}]}], 'blobDateModified': '2023-03-13T15:37:42.000759-04:00', 'id': 'dandiasset:e4032a47-141d-4c4c-84c1-2be3ac5aeb33', 'path': 'bar-renamed', 'identifier': 'e4032a47-141d-4c4c-84c1-2be3ac5aeb33', 'contentUrl': ['https://api.dandiarchive.org/api/assets/e4032a47-141d-4c4c-84c1-2be3ac5aeb33/download/', 'https://dandiarchive.s3.amazonaws.com/blobs/2fd/746/2fd7464f-5459-4c96-a938-27cf13f4d330'], 'contentSize': 4, 'digest': {'dandi:dandi-etag': '517a02191c8c9d1013b48b1f295e03a2-1', 'dandi:sha2-256': 'b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c'}}}
```

the same behavior in swagger for that record:

image

Since it worked for me "manual" attempt in swagger, I think smth in metadata record causes dandi-archive to not perform the action but not complain about that.

### PR DESCRIPTION
**Pull request by waxlamp**
The logic for PUT on asset metadata includes a check to see if the asset is "different" enough to warrant an actual change. This works in part by stripping the supplied metadata of all computed fields, of which `path` is one, and then comparing what remains. This had the effect of barring any "move" type operations (by changing just the `path` value of a metadata and performing a PUT), as changes to the path did not "count" towards being different enough. The workaround was to _also_ change a _non_-computed metadata field; this made the asset different enough to trigger a change, which included the changed path.

The fix is to teach the "is different" function about path-only changes.

Thanks to @AlmightyYakob for his help in figuring this out.

TODO:
- [x] add a test (@AlmightyYakob)

Closes #1682.

### CODE REVIEW

**Comment by AlmightyYakob** [comment]
I've confirmed that the test included in [`65cf41f`](https://github.com/dandi/dandi-archive/pull/1689/commits/65cf41f6b149b230ab8fcdf9d8a20d7a6e434591) fails on master, but succeeds on this branch.

**Comment by AlmightyYakob** [comment]
The tests seem to be failing due to some underlying issue which is also affecting master, and it not a result of this PR.

**Comment by mvandenburgh** [comment]
> The tests seem to be failing due to some underlying issue which is also affecting master, and it not a result of this PR (evidenced via [dandi/dandi-archive/actions/runs/6319690526](https://github.com/dandi/dandi-archive/actions/runs/6319690526)).

#1691 should make CI green again.

**Comment by yarikoptic** [comment]
Let's rebase to see tests pass (or not)?

**Review by danlamanna — APPROVED** [review]

**Comment by satra** [comment]
let's also get this in a release so that @slaytonmarx can fix some of those files.

**Pull request merged**
