### PR TITLE
Update to preferred form of NWBE url

### PR DESCRIPTION
**Pull request by pgleeson**
The new form of this URL has been tested, and it would be great to get this updated on your side.

### CODE REVIEW

**Comment by yarikoptic** [comment]
note: would conflict with https://github.com/dandi/dandi-archive/pull/1706 but easy to resolve.

**Comment by pgleeson** [comment]
Thanks @yarikoptic!

**Comment by yarikoptic** [comment]
@pgleeson would you please be kind to update pr too resolve conflicts, now that we merged that other pr

**Comment by waxlamp** [comment]
The URL looks like what is intended, but I wasn't able to test it (first I got a page that directed me to launch a server; after that I tried again and got a 503).

attn: @pgleeson

**Comment by pgleeson** [comment]
Thanks @yarikoptic @waxlamp. Actually we've discovered an issue with our url construction which causes strange behaviour across subsequent loadings of the same url: https://github.com/OpenSourceBrain/OSBv2/issues/820, which may suggest that the original url you're using is the preferred one. We'll have a new deployment of osbv2 in the next few days and can test more, but closing this for now - ideally no change will be required. 

CC @filippomc

**Pull request closed without merging**
