### PR TITLE
[wip] search design doc with examples

### PR DESCRIPTION
**Pull request by djarecka**
@satra - just to start the discussion and examples

I've added all metadata from assets (e.g. [this](https://api.dandiarchive.org/api/dandisets/000207/versions/0.220216.0323/assets/c6fe83ba-592d-4e84-81c2-10222f346ea3/), but I think I have issues with connecting assets to a specific dataset.

### CODE REVIEW

**Comment by satra** [comment]
are you doing the assets and dandisets using the API or from the s3 bucket? if the s3 bucket 
```
$ aws s3 ls s3://dandiarchive/dandisets/000221/
                           PRE 0.220303.1653/
                           PRE draft/

$ aws s3 ls s3://dandiarchive/dandisets/000221/draft/
2022-03-03 11:53:34     642239 assets.jsonld
2022-03-03 11:53:33     659070 assets.yaml
2022-03-03 11:53:34      13312 collection.jsonld
2022-03-03 11:53:33       3433 dandiset.jsonld
2022-03-03 11:53:31       3406 dandiset.yaml
```
the `collection.jsonld` document should connect each version of dandiset to it's collection of assets.

**Comment by djarecka** [comment]
@satra - do you see the proper connection between assets and dandisets in `tmp_221_dandisets_coll`?

**Comment by satra** [comment]
i see it, but the asset is treated as a string. you can run this query. the object should be an iri.
`SELECT * WHERE {?s prov:hasMember ?o . }`

and this is because we are not generating the proper context: https://github.com/dandi/schema/blob/master/releases/0.6.2/context.json#L221

it's missing the `@type` like this: https://github.com/dandi/schema/blob/master/releases/0.6.2/context.json#L236

to test you, can manually augment the context before conversion.  see this example: https://w3c.github.io/json-ld-syntax/#example-combining-external-and-local-contexts

like this: https://tinyurl.com/y93q6rkr

but we will have to fix those files and the context generation. here is a PR to fix context. you can replace the context value with `https://raw.githubusercontent.com/dandi/schema/cb3bdf785fc487213efc71c5e83ac60dff5ab6a7/releases/0.6.2/context.json` to test it out.

**Comment by djarecka** [comment]
`tmp_221_dandisets_coll_newcontext` uses new context and it looks now much different. When I looked at this visualization:

<details>
  <summary>Click to expand!</summary>
  

```
# Expand From IRIs
CONSTRUCT {
  ?iri ?predicate ?object .
  ?object a ?object_type .
  ?object <tag:stardog:studio:label> ?object_label_0 .
  ?object rdfs:label ?object_label_1 .
  ?object <http://purl.org/dc/elements/1.1/title> ?object_label_2 .
  ?subject ?predicate_2 ?iri .
  ?subject a ?subject_type .
  ?subject <tag:stardog:studio:label> ?subject_label_0 .
  ?subject rdfs:label ?subject_label_1 .
  ?subject <http://purl.org/dc/elements/1.1/title> ?subject_label_2 .
} WHERE {
  VALUES (?iri) {
    (<http://dandiarchive.org/asset/0271f57d-18b8-43fb-b14f-af2698dd37c0>)
  }
  { 
    ?iri ?predicate ?object . 
    OPTIONAL { ?object a ?object_type . }
    OPTIONAL { ?object <tag:stardog:studio:label> ?object_label_0 . }
    OPTIONAL { ?object rdfs:label ?object_label_1 . }
    OPTIONAL { ?object <http://purl.org/dc/elements/1.1/title> ?object_label_2 . }
  }
  UNION {
    ?subject ?predicate_2 ?iri .
    OPTIONAL { ?subject a ?subject_type . }
    OPTIONAL { ?subject <tag:stardog:studio:label> ?subject_label_0 . }
    OPTIONAL { ?subject rdfs:label ?subject_label_1 . }
    OPTIONAL { ?subject <http://purl.org/dc/elements/1.1/title> ?subject_label_2 . }
  }
}
LIMIT 1000
```
</details>

Now I can see that the asset has `prov:hasMamber` as edges!

**Comment by waxlamp** [comment]
@djarecka, @satra: I've converted this to a draft PR, since it's still heavily WIP.

**Comment by waxlamp** [comment]
@djarecka, @satra, what's the status of this PR?

**Comment by satra** [comment]
i think it would good to now transform this doc not to exact sparql queries but the kinds of information needed from search. the queries can still remain at the end of the doc, but it would good to use this to determine the facets we need to search over, how to encode available vs missing information, etc.,.

**Comment by yarikoptic** [comment]
should we may be close this one for now since 
- no activity for almost a year
- unlikely to be taken out of draft any time soon
WDYT @djarecka and @satra ?

**Comment by waxlamp** [comment]
Following Yarik's quiet suggestion, I'm going to go ahead and close this. We can always re-open or extract ideas to somewhere else.

**Pull request closed without merging**
