### PR TITLE
Adding neurosift to external services

### LINKED ISSUE #1646: [Feature]: visualize NWB files with neurosift
[neurosift](https://github.com/scratchrealm/neurosift) is a JS-based neurophysiology data visualization tool created by @magland. It allows for data to be streamed directly from DANDI (or any s3 bucket), and can automatically render visualizations from NWB data files. This is like NWB Widgets, except it is entirely client side visualizations, and does not require us to launch a jupyter kernel in the background.

[Here](https://scratchrealm.github.io/neurosift/#/test) is a WIP example of an automatic visualization of NWB. 

We are still in the process of developing an ideal visualization and optimizing data storage to improve streaming performance. On the web UI side, would it be possible to add neurosift as an "external service" here?
image

### PR DESCRIPTION
**Pull request by satra**
closes #1646

### CODE REVIEW

**Comment by magland** [comment]
As mentioned in #1646 "scratchrealm" needs to be replaced by "flatironinstitute", and the links won't actually work until tomorrow.

**Comment by yarikoptic** [comment]
I have looked at https://deploy-preview-1647--gui-staging-dandiarchive-org.netlify.app/dandiset/200560/draft/files?location=sub-foo and it seems to work :
image
although I am not sure I am yet grasping what it shows, e.g. what is the subject id? whenever metacell after what feels 100x time of that shows the value to be there:
image

**Comment by magland** [comment]
@yarikoptic I have hard-coded the meta information displayed on the left based on a couple nwb files I have tested with. Evidently there are fields that are not being included. I'll open an issue on neurosift.

Also, this example doesn't showcase the visualizations, because the file doesn't have acquisitions data. The capabilities will expand over time.

**Review by waxlamp — APPROVED** [review]

**Comment by waxlamp** [comment]
@satra, I'll leave it to you to merge this if/when you believe it's ready. I'm not doing it myself because I'm not sure if we're waiting on updates to Neurosift before we push this integration live.

**Comment by satra** [comment]
i'm going to merge this and then do a separate PR to indicate what kind of url to provide the service.

**Pull request merged**
