### PR TITLE
Resolve all asset types being evaluated during upload validation

### PR DESCRIPTION
**Pull request by aaronkanzer**
Relates to /linc-archive/pull/34 and https://github.com/dandi/dandi-archive/issues/1814

During validation of `zarr` based datasets, a validation check occurs on the `assetSummary` field in the `dandiset.yaml`

Prior to this PR, the only "assets" evaluated were "blob". In the query that is updated in this PR, the checks for `size` are expanded to not just `blob` but other "asset" types within the Asset model -- see link below:

https://github.com/dandi/dandi-archive/blob/1be249aaff28586e8cd0fadbe2c719a3fb83ef45/dandiapi/api/models/asset.py#L137-L145

Prior to the fix in this PR, the following validation would fail on assets in `dandischema` such as `zarr`: https://github.com/dandi/dandi-schema/blob/bdb7dd681435f1092814041eb01eb4fabe87bf57/dandischema/models.py#L1497

### CODE REVIEW

**Comment by yarikoptic** [comment]
if it is a "Draft:" should it better be a "Draft"? 
image

**Comment by aaronkanzer** [comment]
> if it is a "Draft:" should it better be a "Draft"? image

@yarikoptic Moved to draft -- going to blame lack of coffee on my side for not making this initially a draft 😄

**Comment by yarikoptic** [comment]
@aaronkanzer I have added you to the @dandi/dandiarchive team, so you should be able to push a branch to this fork for a PR to gain access to all the secrets.  Please resubmit this PR

**Comment by aaronkanzer** [comment]
Closing to move code to: https://github.com/dandi/dandi-archive/pull/2062

**Pull request closed without merging**
