### PR TITLE
Resolve broken fixtures in dev dataset script for local Dandi

### PR DESCRIPTION
**Pull request by aaronkanzer**
Validation for creation of Django objects was failing prior to changes when running:

```
docker-compose run --rm django ./manage.py create_dev_dandiset --owner your.email@email.com
```

This PR resolves errors within this script to ensure correct setup locally

### CODE REVIEW

**Comment by yarikoptic** [comment]
Hi @aaronkanzer , thank you for the patch!  As I see that there is a dedicated http://github.com/dandi/dandi-archive/blob/HEAD/dandiapi/api/tests/test_create_dev_dandiset.py and I see it passing recently

```
dandi@drogon:/mnt/backup/dandi/tinuous-logs/dandi-archive/2023/10$ git grep 'test_create_dev' 31
31/github/cron/20231031T002002/8d66efa/CI for backend/2226/2_test (test).txt:2023-10-31T00:24:06.3991432Z dandiapi/api/tests/test_create_dev_dandiset.py::test_create_dev_dandiset PASSED [ 36%]
31/github/cron/20231031T002002/8d66efa/CI for backend/2226/2_test (test).txt:2023-10-31T00:25:58.7490431Z dandiapi/api/tests/test_create_dev_dandiset.py: 1 warning
31/github/cron/20231031T002002/8d66efa/CI for backend/2226/test (test)/6_Run tests.txt:2023-10-31T00:24:06.3991380Z dandiapi/api/tests/test_create_dev_dandiset.py::test_create_dev_dandiset PASSED [ 36%]
31/github/cron/20231031T002002/8d66efa/CI for backend/2226/test (test)/6_Run tests.txt:2023-10-31T00:25:58.7490425Z dandiapi/api/tests/test_create_dev_dandiset.py: 1 warning

```

could you 
- elaborate on the failure (is it a new fail or something "introduced" recently?)
- see if you can adjust/extend that test so it demonstrates prior issue which this PR fixes?

**Comment by waxlamp** [comment]
I second @yarikoptic's requests -- without knowing the exact failure you encountered, it's hard to review this and understand the added value. Thanks @aaronkanzer!

**Comment by yarikoptic** [comment]
Ping @aaronkanzer to discover more of the reason here

**Comment by aaronkanzer** [comment]
Closing due to duplicative code in https://github.com/dandi/dandi-archive/pull/1809

**Pull request closed without merging**
