### PR TITLE
ENH: expose force for zarr_ingest API call

### PR DESCRIPTION
**Pull request by yarikoptic**
Reference for the need:  https://github.com/dandi/dandi-archive/issues/1347#issuecomment-1294933546

TODOs if decide to proceed
- [ ] check that help_text is the right way to go to document it. (if it is -- why other similar fields are not documented anywhere?)
- [ ] add test
- [ ] ensure correct response/reaction upon use by non-admin user (ATM taken the same behavior as for another admin-only operation of creating dandiset with specified id)

### CODE REVIEW

**Comment by waxlamp** [comment]
It turns out we already have appropriate management commands in the codebase to initiate forced reingestion. Rather than update the API to do something we can already do as admins, I'm going to close this PR.

**Comment by yarikoptic** [comment]
how can we do this as admins @waxlamp?

**Comment by yarikoptic** [comment]
FTR, I have tried in admin interface but that didn't work as I outlined in https://github.com/dandi/dandi-archive/issues/1347#issuecomment-1296010873 .

**Comment by waxlamp** [comment]
There is a management command that does the force reingestion. The admin console only supports *non*-force reingestion (i.e., for Zarrs that have not yet been ingested at all). As such, it is not a very useful feature, and in the name of simplification we may even think about removing it (probably after we improve the general process for Zarrs, such that we won't need a feature like this as often).

In terms of yesterday's discussion: the management command is the technician's secret button to initiate force reingestion (which means "jumping wires on the circuit board with a needle" isn't actually necessary), while the admin console has something akin to the "close door" button in an elevator.

**Pull request closed without merging**
