### PR TITLE
Fix responsiveness of v-app-bar

### LINKED ISSUE #934: Fix navbar responsive design styling
The navbar behaves strangely when the window width is a certain size (i.e. buttons are misplaced/wrap incorrectly, the DANDI logo shrinks too much, etc). There's also some inconsistent behavior between Chromium-based browsers and Firefox. Overall, it seems like the navbar styling needs to be reworked significantly.

### PR DESCRIPTION
**Pull request by jtomeck**
Fixes #934 

@waxlamp A little late because I needed Mike's help on some stuff, but the navbar works responsively and in Firefox now. I just need @mvandenburgh to fix some of the logic that I broke in the mobile menu to make the links work and this will be all set.

Thanks in advance, Mike!

### CODE REVIEW

**Comment by waxlamp** [comment]
Fantastic! Is this ready for review? If so, could you click the button, @jtomeck?

**Comment by jtomeck** [comment]
> Fantastic! Is this ready for review? If so, could you click the button, @jtomeck?

Not ready until Mike is able to have a look at how badly I broke the mobile menu items haha. I need a lot of help with the logic, since the structure changed to match the proper use of `v-list` subcomponents.

**Comment by waxlamp** [comment]
Gotcha, thanks.

**Review by mvandenburgh — COMMENTED** [review]
Looks great! @jtomeck I pushed a change to add the links back to the mobile menu. The issue was that the navbar is composed of both "real links" which are referred to via the `href` attribute, as well as `vue-router` links which are handled differently by the SPA.

**Comment by jtomeck** [comment]
Thanks Mike! @waxlamp I just marked this ready for review.

**Review by mvandenburgh — APPROVED** [review]
I missed setting the `exact` prop, so the links in the mobile menu were being highlighted when they shouldn't have been - I pushed up that change as well. Everything looks good to me!

**Comment by jtomeck** [comment]
@waxlamp let me know if you think this is good to merge!

**Review by waxlamp — APPROVED** [review]

**Pull request merged**
